routes/web.php
<?php

Auth::routes();
Route::get('/', 'HomeController@index');
Route::get('/qgrid', 'QgridController@index');
Route::get('/qgrid/add', 'QgridController@create')->name('/qgrid/add');
Route::get('/qgrid/export_csv', 'QgridController@export_csv')->name('/qgrid/export_csv');
Route::get('/qgrid/export_json', 'QgridController@export_json')->name('/qgrid/export_json');
Route::post('/qgrid/update{id}', 'QgridController@update')->name('/qgrid/update');
Route::post('/qgrid/delete{id}', 'QgridController@delete')->name('/qgrid/delete');
Route::get('page/add', 'PageController@create');
Route::get('page/{page}/delete', [
    'as'   => 'page.delete',
    'uses' => 'PageController@destroy',
]);
Route::resource('/page', 'PageController');

Route::post('fileUpload', ['as'=>'fileUpload','uses'=>'HomeController@fileUpload']);

function is_active_sorter($key, $direction = 'ASC')
{
    if (request('sortby') == $key && request('sortdir') == $direction) {
        return true;
    }

    return false;
}

resources/views/page/create.blade.php
@extends('layouts.app')

@section('content')
  <div class="container">

    <form method="POST" action="/page">

      <div class="clearfix">
        <div class="pull-left">
          <div class="lead">
            <strong>Add new page</strong>
          </div>
        </div>
        <div class="pull-right">
          <button type="submit" class="btn btn-success">Save</button>
          <a href="/page" class="btn btn-default">Back to list</a>
        </div>
      </div>
      <hr>

      @include('page.form')
    </form>

  </div>
@endsection

resources/views/page/edit.blade.php
@extends('layouts.app')

@section('content')
  <div class="container">

    <form method="POST" action="/page/{{ $page->id }}">

      <div class="clearfix">
        <div class="pull-left">
          <div class="lead">
            <strong>Edit page</strong>
            <small>{{ $page->title }}</small>
          </div>
        </div>
        <div class="pull-right">
          <button type="submit" class="btn btn-success">Save</button>
          <a href="/page" class="btn btn-default">Back to list</a>
        </div>
      </div>
      <hr>

      {!! method_field('PUT') !!}
      @include('page.form')
    </form>

  </div>
@endsection

resources/views/page/form.blade.php
{!! csrf_field() !!}

<div class="form-group {{ $errors->has('url') ? 'has-error' : '' }}">

  <label for="url" class="control-label">
    {{ trans('url') }}
  </label>

  <input type="url"
         name="url"
         id="url"
         value="{{ old('url', @$page->url) }}"
         placeholder="url"
         required
         class="form-control">

  @if ($errors->has('url'))
    <div class="help-block">
      {{ $errors->first('url') }}
    </div>
  @endif
</div>

<div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">

  <label for="name" class="control-label">
    {{ trans('name') }}
  </label>

  <input type="text"
         name="name"
         id="name"
         value="{{ old('name', @$page->name) }}"
         placeholder="name"
         required
         class="form-control">

  @if ($errors->has('name'))
    <div class="help-block">
      {{ $errors->first('name') }}
    </div>
  @endif
</div>

<div class="form-group {{ $errors->has('title') ? 'has-error' : '' }}">

  <label for="title" class="control-label">
    {{ trans('title') }}
  </label>

  <input type="text"
         name="title"
         id="title"
         value="{{ old('title', @$page->title) }}"
         placeholder="title"
         required
         class="form-control">

  @if ($errors->has('title'))
    <div class="help-block">
      {{ $errors->first('title') }}
    </div>
  @endif
</div>

<div class="form-group {{ $errors->has('content') ? 'has-error' : '' }}">

  <label for="content" class="control-label">
    {{ trans('content') }}
  </label>

      <textarea
          name="content"
          id="content"
          placeholder="content"
          required
          class="form-control">{{ old('content', @$page->content) }}</textarea>

  @if ($errors->has('content'))
    <div class="help-block">
      {{ $errors->first('content') }}
    </div>
  @endif
</div>

<div class="form-group">
  <button type="submit" class="btn btn-success">Save</button>
  <a href="/page" class="btn btn-default">Back to list</a>
</div>

resources/views/page/index.blade.php
@extends('layouts.app')

@section('content')
  <div class="container">

    <div class="clearfix">
      <div class="pull-left">
        <div class="lead">Page</div>
      </div>
      <div class="pull-right">
        <a href="/page/add" class="btn btn-success">Add new</a>
      </div>
    </div>

    <hr>

    <table class="table table-bordered table-hover table-striped">
      <thead>
      <tr>
        <th class="col-xs-1">
          ID
          <div class="pull-right">
            <a href="?sortby=id&sortdir=ASC"
               class="btn btn-xs {{ is_active_sorter('id', 'ASC') ? 'btn-primary' : 'btn-default' }}">
              <i class="fa fa-arrow-up"></i>
            </a>
            <a href="?sortby=id&sortdir=DESC"
               class="btn btn-xs {{ is_active_sorter('id', 'DESC') ? 'btn-primary' : 'btn-default' }}">
              <i class="fa fa-arrow-down"></i>
            </a>
          </div>
        </th>
        <th class="col-xs-3">
          Page title
          <div class="pull-right">
            <a href="?sortby=title&sortdir=ASC"
               class="btn btn-xs {{ is_active_sorter('title', 'ASC') ? 'btn-primary' : 'btn-default' }}">
              <i class="fa fa-arrow-up"></i>
            </a>
            <a href="?sortby=title&sortdir=DESC"
               class="btn btn-xs {{ is_active_sorter('title', 'DESC') ? 'btn-primary' : 'btn-default' }}">
              <i class="fa fa-arrow-down"></i>
            </a>
          </div>
        </th>
        <th class="col-xs-3">
          Last modified
          <div class="pull-right">
            <a href="?sortby=updated_at&sortdir=ASC"
               class="btn btn-xs {{ is_active_sorter('updated_at', 'ASC') ? 'btn-primary' : 'btn-default' }}">
              <i class="fa fa-arrow-up"></i>
            </a>
            <a href="?sortby=updated_at&sortdir=DESC"
               class="btn btn-xs {{ is_active_sorter('updated_at', 'DESC') ? 'btn-primary' : 'btn-default' }}">
              <i class="fa fa-arrow-down"></i>
            </a>
          </div>
        </th>
        <th class="col-xs-2">
          Action
        </th>
      </tr>
      </thead>
      <tbody>
      @foreach($pages as $page)
        <tr>
          <td>{{ $page->id }}</td>
          <td>
            <a href="/page/{{ $page->id }}">{{ $page->title }}</a>
          </td>
          <td>
            <time class="timeago" datetime="{{ $page->updated_at->toIso8601String() }}"
                  title="{{ $page->updated_at->toDayDateTimeString() }}">
              {{ $page->updated_at->diffForHumans() }}
            </time>
          </td>
          <td>
            <div class="input-group-btn">
              <a href="{{ route('page.edit', $page->id) }}" class="btn btn-primary">Edit</a>
              <a href="{{ route('page.delete', $page->id) }}" class="btn btn-danger"
                 onclick="return confirm('Are you sure to delete this page?');">
                Delete
              </a>
            </div>
          </td>
        </tr>
      @endforeach
      </tbody>
    </table>

    <div class="text-center">
      {!! $pages->appends(request()->except('page'))->links() !!}
    </div>

  </div>
@endsection

resources/views/page/show.blade.php
@extends('layouts.app')

@section('content')

  <div class="container">

    <h2>{{ $page->title }}</h2>

    <div>
      Posted by {{ $page->name }}
      <time class="timeago" datetime="{{ $page->updated_at->toIso8601String() }}"
            title="{{ $page->updated_at->toDayDateTimeString() }}">
        {{ $page->updated_at->diffForHumans() }}
      </time>
    </div>

    <hr>

    <div>
      {!! $page->content !!}
    </div>

  </div>

@endsection